name: cable
description: >
  An extensible and simple logging framework.
version: 0.1.0
authors:
  - Matan Lurey <matanl@google.com>
homepage: https://github.com/matanlurey/cable

environment:
  sdk: ">=1.24.0 <2.0.0"

dependencies:
  meta: ^1.1.0

dev_dependencies:
  test: ^0.12.0
